# Generated by Django 3.0.7 on 2021-12-14 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsfeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsfeedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('file_type', models.CharField(choices=[('image', 'image'), ('video', 'video'), ('audio', 'audio'), ('document', 'document'), ('other', 'other')], default='other', max_length=10)),
                ('newsfeed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='newsfeed.Newsfeed')),
            ],
        ),
    ]
